# 网站 | website
language: zh-CN
favicon: /images/favicon.ico
logo:
title: blog

# 菜单 | menu
menu:
  Home: /
  Archive: /archive/
  About: /about/

# 轮播图 | swiper
swiper:
  image: /images/swiper.jpg
  title: 轮播图

# 页脚 | footer
footer:
  copyright: 版权所有 © 2025 Plutavian
  powered: 由 Hexo 驱动
