# 网站 | website
favicon: /images/favicon.ico
logo:
title: YoruKumo

# 菜单 | menu
menu:
  Home: /
  Archive: /archive
  Tag: /tag
  About: /about

# 轮播图 | swiper
swiper:
  image: /images/swiper.jpg
  title: 轮播图

# 页面布局
layout:
  tag: tag-detail
  archive: archive
  category: category
  about: about

# 页脚 | footer
footer:
  count:
  since: 2025-01-01
  authorLink: https://asukacc.github.io
